# 导入 (import)

In [34]:
import pandas as pd

"""
处理 jsonl 为 pandas dataframe
Process jsonl to pandas dataframe
"""
words_df = pd.read_json("./crawler_output.jsonl", orient="records", lines=True)
words_df.head()

,word,part_of_speech,phonetic_symbol,definitions
0,RN,noun,"[/ˌɑːrˈen/, /ˌɑːrˈen/]","[{'cefr': '[ C ] US', 'definition': {'en': 'a ..."
1,R.N.,noun [ C ],"[/ˌɑːrˈen/, /ˌɑːrˈen/]","[{'cefr': '', 'definition': {'en': 'abbreviati..."
2,riyal,noun [ C ],"[/riˈɑːl/, /riːˈjɑːl/]","[{'cefr': '', 'definition': {'en': 'the standa..."
3,rivulet,noun [ C ],"[/ˈrɪv.jə.lət/, /ˈrɪv.jə.lət/]","[{'cefr': '', 'definition': {'en': 'a very sma..."
4,riviera,noun [ C ],"[/rɪv.iˈeə.rə/, /rɪv.iˈer.ə/]","[{'cefr': '', 'definition': {'en': 'an area of..."

# 预处理

In [35]:
words_df.rename(columns={"word": "spelling"}, inplace=True)
words_df = words_df.astype(
    {
        "spelling": "string",
        "part_of_speech": "string",
        "phonetic_symbol": object,
        "definitions": object,
    }
)

print(words_df.shape)
words_df.head()

(73220, 4)

,spelling,part_of_speech,phonetic_symbol,definitions
0,RN,noun,"[/ˌɑːrˈen/, /ˌɑːrˈen/]","[{'cefr': '[ C ] US', 'definition': {'en': 'a ..."
1,R.N.,noun [ C ],"[/ˌɑːrˈen/, /ˌɑːrˈen/]","[{'cefr': '', 'definition': {'en': 'abbreviati..."
2,riyal,noun [ C ],"[/riˈɑːl/, /riːˈjɑːl/]","[{'cefr': '', 'definition': {'en': 'the standa..."
3,rivulet,noun [ C ],"[/ˈrɪv.jə.lət/, /ˈrɪv.jə.lət/]","[{'cefr': '', 'definition': {'en': 'a very sma..."
4,riviera,noun [ C ],"[/rɪv.iˈeə.rə/, /rɪv.iˈer.ə/]","[{'cefr': '', 'definition': {'en': 'an area of..."

# 展开音标

In [36]:
phonetic_symbols = pd.DataFrame(
    words_df["phonetic_symbol"].tolist(),
    columns=["phonetic_bre", "phonetic_ame"],
)


words_df = pd.concat(
    [words_df.drop("phonetic_symbol", axis=1), phonetic_symbols], axis=1
)
words_df = words_df.astype({"phonetic_bre": "string", "phonetic_ame": "string"})

print(words_df.shape)
words_df.head()

(73220, 5)

,spelling,part_of_speech,definitions,phonetic_bre,phonetic_ame
0,RN,noun,"[{'cefr': '[ C ] US', 'definition': {'en': 'a ...",/ˌɑːrˈen/,/ˌɑːrˈen/
1,R.N.,noun [ C ],"[{'cefr': '', 'definition': {'en': 'abbreviati...",/ˌɑːrˈen/,/ˌɑːrˈen/
2,riyal,noun [ C ],"[{'cefr': '', 'definition': {'en': 'the standa...",/riˈɑːl/,/riːˈjɑːl/
3,rivulet,noun [ C ],"[{'cefr': '', 'definition': {'en': 'a very sma...",/ˈrɪv.jə.lət/,/ˈrɪv.jə.lət/
4,riviera,noun [ C ],"[{'cefr': '', 'definition': {'en': 'an area of...",/rɪv.iˈeə.rə/,/rɪv.iˈer.ə/

# 展开释义

In [37]:
assert (
    words_df["definitions"].isnull().sum() == 0
), "数据处理错误，存在缺失的 definitions！Data processing error, missing definitions!"

words_df = words_df.explode("definitions")
definitions = pd.json_normalize(words_df["definitions"])
definitions = definitions.rename(
    columns={"definition.en": "def_src", "definition.zh": "def_tgt"}
)
definitions = definitions.drop(columns=["cefr"])

words_df = pd.concat([words_df.drop(columns=["definitions"]), definitions], axis=1)
words_df = words_df.astype({"def_src": "string", "def_tgt": "string"})

assert len(definitions) == len(
    words_df
), "数据处理错误，行数不匹配！Data processing error, row count mismatch!"

print(words_df.shape)
words_df.head()

(99449, 7)

,spelling,part_of_speech,phonetic_bre,phonetic_ame,examples,def_src,def_tgt
0,RN,noun,/ˌɑːrˈen/,/ˌɑːrˈen/,[{'en': 'An RN makes about $30 an hour in this...,a \n \n registered nurse ; als...,注册护士（可用于姓名后）
0,RN,noun,/ˌɑːrˈen/,/ˌɑːrˈen/,"[{'en': 'Captain H. Doughty, RN', 'zh': '英国皇家海...",abbreviation for Royal Navy: used especially a...,英国皇家海军（尤用于海军军官姓名后，Royal Navy的缩写）
1,R.N.,noun [ C ],/ˌɑːrˈen/,/ˌɑːrˈen/,[],abbreviation for\n \n registere...,注册护士（registered nurse的缩写）
2,riyal,noun [ C ],/riˈɑːl/,/riːˈjɑːl/,[],the standard unit of money used in Saudi Arabi...,里亚尔（沙特阿拉伯和卡塔尔的货币单位）
3,rivulet,noun [ C ],/ˈrɪv.jə.lət/,/ˈrɪv.jə.lət/,[{'en': 'Rivulets of sweat/rain/blood ran down...,a very small stream or flow of liquid,小溪;小河;细流

# 展开例子

In [38]:
words_df = words_df.explode("examples")

# 处理 examples 列，空的例子用 {} 填充，方便继续 json normalize 展开
words_df["examples"] = words_df["examples"].apply(
    lambda x: x if isinstance(x, dict) else {}
)
examples = pd.json_normalize(words_df["examples"])
examples = examples.rename(columns={"en": "ex_src", "zh": "ex_tgt"})

words_df = pd.concat([words_df.drop(columns=["examples"]), examples], axis=1)
words_df = words_df.astype({"ex_src": "string", "ex_tgt": "string"})
words_df["ex_src"] = words_df["ex_src"].fillna("")
words_df["ex_tgt"] = words_df["ex_tgt"].fillna("")

assert len(examples) == len(
    words_df
), "数据处理错误，行数不匹配！Data processing error, row count mismatch!"
print(words_df.shape)
words_df.head()

(155003, 8)

,spelling,part_of_speech,phonetic_bre,phonetic_ame,def_src,def_tgt,ex_src,ex_tgt
0,RN,noun,/ˌɑːrˈen/,/ˌɑːrˈen/,a \n \n registered nurse ; als...,注册护士（可用于姓名后）,An RN makes about $30 an hour in this city.,在这座城市里一名注册护士的时薪约为30美元。
0,RN,noun,/ˌɑːrˈen/,/ˌɑːrˈen/,a \n \n registered nurse ; als...,注册护士（可用于姓名后）,"Alice Brody, RN",注册护士爱丽丝·布罗第
0,RN,noun,/ˌɑːrˈen/,/ˌɑːrˈen/,abbreviation for Royal Navy: used especially a...,英国皇家海军（尤用于海军军官姓名后，Royal Navy的缩写）,"Captain H. Doughty, RN",英国皇家海军上校 H.道蒂
1,R.N.,noun [ C ],/ˌɑːrˈen/,/ˌɑːrˈen/,abbreviation for\n \n registere...,注册护士（registered nurse的缩写）,,
2,riyal,noun [ C ],/riˈɑːl/,/riːˈjɑːl/,the standard unit of money used in Saudi Arabi...,里亚尔（沙特阿拉伯和卡塔尔的货币单位）,,

# 清洗（Cleaning）

In [39]:
import re

def clean(input: str) -> str:
    # 去除多余的行
    # Remove unnecessary new lines
    input = re.sub(r"\s*\n", " ", input)
    
    # 去除没必要的空格
    # Remove unnecessary spaces
    result: str = ""
    str_list = re.split(r"\s+", input)
    str_list_len = len(str_list)
    for i, sub_str in enumerate(str_list):
        if i == str_list_len - 1:
            result += str_list[-1]
        else:
            result += sub_str + " "
    return result

def assert_is_not_null_or_empty(s: pd.Series) -> bool:
    """
    判断字符串是否是空或者者全是空白的字符串
    Determine if the string is empty or consists entirely of whitespace characters
    """
    return s.isnull().sum() > 0 or s == ""

def assert_not_blank_just_empty(s: pd.Series) -> None:
    """
    应该清洗后的空字符串不是空白，应该是空字符串
    """
    assert s.str.match(r"^\s+$").sum() == 0, "数据处理错误，存在空白的字符串！Data processing error, blank string exists!"

def assert_not_null(s: pd.Series) -> None:
    """
    ID 回填后不应该存在缺失值
    """
    assert s.isnull().sum() == 0, "数据处理错误，存在缺失的 ID！Data processing error, missing id exists!"


words_df = words_df.reset_index(drop=True)
words_df["spelling"] = words_df["spelling"].apply(clean)
words_df["phonetic_bre"] = words_df["phonetic_bre"].apply(clean)
words_df["phonetic_ame"] = words_df["phonetic_ame"].apply(clean)
words_df["part_of_speech"] = words_df["part_of_speech"].apply(clean)
words_df["def_src"] = words_df["def_src"].apply(clean)
words_df["def_tgt"] = words_df["def_tgt"].apply(clean)
words_df["ex_src"] = words_df["ex_src"].apply(clean)
words_df["ex_tgt"] = words_df["ex_tgt"].apply(clean)
words_df = words_df.drop_duplicates()

# spelling 不可能是空或者者全是空白的字符串
assert_not_blank_just_empty(words_df["phonetic_bre"] )
assert_not_blank_just_empty(words_df["phonetic_ame"] )
assert_not_blank_just_empty(words_df["part_of_speech"] )
assert_not_blank_just_empty(words_df["def_src"] )
assert_not_blank_just_empty(words_df["def_tgt"] )
assert_not_blank_just_empty(words_df["ex_src"] )
assert_not_blank_just_empty(words_df["ex_tgt"] )

# schema 约束检查
assert_is_not_null_or_empty(words_df["spelling"] )
assert_is_not_null_or_empty(words_df["part_of_speech"] )

print(words_df.shape)
words_df.head()

(154170, 8)

,spelling,part_of_speech,phonetic_bre,phonetic_ame,def_src,def_tgt,ex_src,ex_tgt
0,RN,noun,/ˌɑːrˈen/,/ˌɑːrˈen/,a registered nurse ; also used after the name ...,注册护士（可用于姓名后）,An RN makes about $30 an hour in this city.,在这座城市里一名注册护士的时薪约为30美元。
1,RN,noun,/ˌɑːrˈen/,/ˌɑːrˈen/,a registered nurse ; also used after the name ...,注册护士（可用于姓名后）,"Alice Brody, RN",注册护士爱丽丝·布罗第
2,RN,noun,/ˌɑːrˈen/,/ˌɑːrˈen/,abbreviation for Royal Navy: used especially a...,英国皇家海军（尤用于海军军官姓名后，Royal Navy的缩写）,"Captain H. Doughty, RN",英国皇家海军上校 H.道蒂
3,R.N.,noun [ C ],/ˌɑːrˈen/,/ˌɑːrˈen/,abbreviation for registered nurse,注册护士（registered nurse的缩写）,,
4,riyal,noun [ C ],/riˈɑːl/,/riːˈjɑːl/,the standard unit of money used in Saudi Arabi...,里亚尔（沙特阿拉伯和卡塔尔的货币单位）,,

# 拆表为符合数据库定义的 schema 进行导出

In [40]:
import time

epoch_ms = time.time_ns() // 1_000_000

# 生成从 1 开始的连续整数主键，供官方词典 ETL 输出使用
def int_id_series(n: int) -> pd.Series:
    return pd.Series(range(1, n + 1), dtype="int64")

def assert_words_df_not_duplicated() -> bool:
    assert (
        words_df.duplicated().sum() == 0
    ), "数据处理错误，存在重复的行！Data processing error, duplicated rows exist!"

def str_is_empty(s: pd.Series) -> pd.Series:
    return s.isnull() | (s == "")

## words 表

In [41]:
words_tb = words_df[["spelling", "phonetic_bre", "phonetic_ame"]]
words_tb = words_tb.drop_duplicates(subset=["spelling"]).reset_index(drop=True)

words_tb = words_tb.reset_index(drop=True)
words_tb.insert(loc=0, column="word_id", value=list(int_id_series(len(words_tb))))
words_tb["created_at"] = epoch_ms
words_tb["updated_at"] = epoch_ms

# 注意后面还得生成一个词条版本
#words_tb.to_json(
#    "./words.jsonl", orient="records", lines=True, force_ascii=False
#)

print(words_tb.shape)
words_tb.head()

(67984, 6)

,word_id,spelling,phonetic_bre,phonetic_ame,created_at,updated_at
0,1,RN,/ˌɑːrˈen/,/ˌɑːrˈen/,1786116073665,1786116073665
1,2,R.N.,/ˌɑːrˈen/,/ˌɑːrˈen/,1786116073665,1786116073665
2,3,riyal,/riˈɑːl/,/riːˈjɑːl/,1786116073665,1786116073665
3,4,rivulet,/ˈrɪv.jə.lət/,/ˈrɪv.jə.lət/,1786116073665,1786116073665
4,5,riviera,/rɪv.iˈeə.rə/,/rɪv.iˈer.ə/,1786116073665,1786116073665

In [42]:
# 回填
words_df = words_df.merge(
    words_tb[["spelling", "word_id"]],
    on="spelling",
    how="left",
    validate="many_to_one",
)

assert_not_null(words_df["word_id"])
assert_words_df_not_duplicated()

print(words_df.shape)
words_df.head()

(154170, 9)

,spelling,part_of_speech,phonetic_bre,phonetic_ame,def_src,def_tgt,ex_src,ex_tgt,word_id
0,RN,noun,/ˌɑːrˈen/,/ˌɑːrˈen/,a registered nurse ; also used after the name ...,注册护士（可用于姓名后）,An RN makes about $30 an hour in this city.,在这座城市里一名注册护士的时薪约为30美元。,1
1,RN,noun,/ˌɑːrˈen/,/ˌɑːrˈen/,a registered nurse ; also used after the name ...,注册护士（可用于姓名后）,"Alice Brody, RN",注册护士爱丽丝·布罗第,1
2,RN,noun,/ˌɑːrˈen/,/ˌɑːrˈen/,abbreviation for Royal Navy: used especially a...,英国皇家海军（尤用于海军军官姓名后，Royal Navy的缩写）,"Captain H. Doughty, RN",英国皇家海军上校 H.道蒂,1
3,R.N.,noun [ C ],/ˌɑːrˈen/,/ˌɑːrˈen/,abbreviation for registered nurse,注册护士（registered nurse的缩写）,,,2
4,riyal,noun [ C ],/riˈɑːl/,/riːˈjɑːl/,the standard unit of money used in Saudi Arabi...,里亚尔（沙特阿拉伯和卡塔尔的货币单位）,,,3

## word_poses 表

In [43]:
word_poses_tb = words_df[["word_id", "part_of_speech"]]
word_poses_tb = word_poses_tb.drop_duplicates(subset=["word_id", "part_of_speech"])

word_poses_tb = word_poses_tb.reset_index(drop=True)
word_poses_tb.insert(
    loc=0,
    column="pose_id",
    # 
    value=list(int_id_series(len(word_poses_tb)))
)

word_poses_tb["created_at"] = epoch_ms
word_poses_tb["updated_at"] = epoch_ms

print(word_poses_tb.shape)
word_poses_tb.head()

(73208, 5)

   pose_id  word_id part_of_speech     created_at     updated_at
0        1        1           noun  1786116073665  1786116073665
1        2        2     noun [ C ]  1786116073665  1786116073665
2        3        3     noun [ C ]  1786116073665  1786116073665
3        4        4     noun [ C ]  1786116073665  1786116073665
4        5        5     noun [ C ]  1786116073665  1786116073665

In [44]:
# 回填
words_df = words_df.merge(
    word_poses_tb[["word_id", "part_of_speech", "pose_id"]],
    on=["word_id", "part_of_speech"],
    how="left",
    validate="many_to_one",
)
assert_not_null(words_df["pose_id"])

print(words_df.shape)
words_df.head()

(154170, 10)

,spelling,part_of_speech,phonetic_bre,phonetic_ame,def_src,def_tgt,ex_src,ex_tgt,word_id,pose_id
0,RN,noun,/ˌɑːrˈen/,/ˌɑːrˈen/,a registered nurse ; also used after the name ...,注册护士（可用于姓名后）,An RN makes about $30 an hour in this city.,在这座城市里一名注册护士的时薪约为30美元。,1,1
1,RN,noun,/ˌɑːrˈen/,/ˌɑːrˈen/,a registered nurse ; also used after the name ...,注册护士（可用于姓名后）,"Alice Brody, RN",注册护士爱丽丝·布罗第,1,1
2,RN,noun,/ˌɑːrˈen/,/ˌɑːrˈen/,abbreviation for Royal Navy: used especially a...,英国皇家海军（尤用于海军军官姓名后，Royal Navy的缩写）,"Captain H. Doughty, RN",英国皇家海军上校 H.道蒂,1,1
3,R.N.,noun [ C ],/ˌɑːrˈen/,/ˌɑːrˈen/,abbreviation for registered nurse,注册护士（registered nurse的缩写）,,,2,2
4,riyal,noun [ C ],/riˈɑːl/,/riːˈjɑːl/,the standard unit of money used in Saudi Arabi...,里亚尔（沙特阿拉伯和卡塔尔的货币单位）,,,3,3

## definitions 表

In [45]:
definitions_tb = words_df[["pose_id", "def_src", "def_tgt"]].drop_duplicates()
definitions_tb = definitions_tb.rename(columns={"pose_id": "word_pos_id"})

definitions_tb = definitions_tb.reset_index(drop=True)
definitions_tb.insert(loc=0, column="def_id", value=list(int_id_series(len(definitions_tb))))
definitions_tb["created_at"] = epoch_ms
definitions_tb["updated_at"] = epoch_ms

print(definitions_tb.shape)
definitions_tb.head()

(99244, 6)

,def_id,word_pos_id,def_src,def_tgt,created_at,updated_at
0,1,1,a registered nurse ; also used after the name ...,注册护士（可用于姓名后）,1786116073665,1786116073665
1,2,1,abbreviation for Royal Navy: used especially a...,英国皇家海军（尤用于海军军官姓名后，Royal Navy的缩写）,1786116073665,1786116073665
2,3,2,abbreviation for registered nurse,注册护士（registered nurse的缩写）,1786116073665,1786116073665
3,4,3,the standard unit of money used in Saudi Arabi...,里亚尔（沙特阿拉伯和卡塔尔的货币单位）,1786116073665,1786116073665
4,5,4,a very small stream or flow of liquid,小溪;小河;细流,1786116073665,1786116073665

In [46]:
# 回填
words_df = words_df.merge(
    definitions_tb[["def_id", "word_pos_id", "def_src", "def_tgt"]],
    left_on=["pose_id", "def_src", "def_tgt"],
    right_on=["word_pos_id", "def_src", "def_tgt"],
    how="left",
    validate="many_to_one",
)

# 已经有 pose_id 了，这个是 join 临时用的
words_df = words_df.drop(columns=["word_pos_id"])

assert_not_null(words_df["def_id"])
assert_words_df_not_duplicated()

print(words_df.shape)
words_df.head()

(154170, 11)

,spelling,part_of_speech,phonetic_bre,phonetic_ame,def_src,def_tgt,ex_src,ex_tgt,word_id,pose_id,def_id
0,RN,noun,/ˌɑːrˈen/,/ˌɑːrˈen/,a registered nurse ; also used after the name ...,注册护士（可用于姓名后）,An RN makes about $30 an hour in this city.,在这座城市里一名注册护士的时薪约为30美元。,1,1,1
1,RN,noun,/ˌɑːrˈen/,/ˌɑːrˈen/,a registered nurse ; also used after the name ...,注册护士（可用于姓名后）,"Alice Brody, RN",注册护士爱丽丝·布罗第,1,1,1
2,RN,noun,/ˌɑːrˈen/,/ˌɑːrˈen/,abbreviation for Royal Navy: used especially a...,英国皇家海军（尤用于海军军官姓名后，Royal Navy的缩写）,"Captain H. Doughty, RN",英国皇家海军上校 H.道蒂,1,1,2
3,R.N.,noun [ C ],/ˌɑːrˈen/,/ˌɑːrˈen/,abbreviation for registered nurse,注册护士（registered nurse的缩写）,,,2,2,3
4,riyal,noun [ C ],/riˈɑːl/,/riːˈjɑːl/,the standard unit of money used in Saudi Arabi...,里亚尔（沙特阿拉伯和卡塔尔的货币单位）,,,3,3,4

## examples 表

In [47]:
examples_tb = words_df[["def_id", "ex_src", "ex_tgt"]].drop_duplicates()

# drop 掉同时没有中英文例句的行
examples_tb = examples_tb[
    ~(str_is_empty(examples_tb["ex_src"]) & str_is_empty(examples_tb["ex_tgt"]))
]

assert (
    examples_tb[
        (str_is_empty(examples_tb["ex_src"]) & str_is_empty(examples_tb["ex_tgt"]))
    ].shape[0]
    == 0
), "数据处理错误，存在缺失的 ex_src 或 ex_tgt！Data processing error, missing ex_src or ex_tgt!"

examples_tb = examples_tb.reset_index(drop=True)
examples_tb.insert(loc=0, column="exp_id", value=list(int_id_series(len(examples_tb))))
examples_tb["created_at"] = epoch_ms
examples_tb["updated_at"] = epoch_ms
assert_not_null(examples_tb["def_id"])

print(examples_tb.shape)
examples_tb.head()

(129186, 6)

,exp_id,def_id,ex_src,ex_tgt,created_at,updated_at
0,1,1,An RN makes about $30 an hour in this city.,在这座城市里一名注册护士的时薪约为30美元。,1786116073665,1786116073665
1,2,1,"Alice Brody, RN",注册护士爱丽丝·布罗第,1786116073665,1786116073665
2,3,2,"Captain H. Doughty, RN",英国皇家海军上校 H.道蒂,1786116073665,1786116073665
3,4,5,Rivulets of sweat/rain/blood ran down his face.,汗水／雨水／鲜血从他脸上不住地流下来。,1786116073665,1786116073665
4,5,6,the French/Italian/Cornish riviera,法国／意大利／科尼什海滨度假胜地,1786116073665,1786116073665

## 词条版本

In [48]:
# 官方词条内容版本；同一 word_id 的释义/例句/音标发生变更时递增
WORD_ENTRY_VERSION = 1

## 表导出

In [49]:
words_tb = words_tb.reset_index(drop=True)
if "entry_version" in words_tb.columns:
    words_tb["entry_version"] = WORD_ENTRY_VERSION
else:
    words_tb.insert(
        loc=2,
        column="entry_version",
        value=WORD_ENTRY_VERSION,
    )

assert (
    words_tb["entry_version"].notnull().all()
), "数据处理错误，存在缺失的 entry_version！Data processing error, missing entry_version!"

print(words_tb.shape)
words_tb.head()

(67984, 7)

,word_id,spelling,entry_version,phonetic_bre,phonetic_ame,created_at,updated_at
0,1,RN,1,/ˌɑːrˈen/,/ˌɑːrˈen/,1786116073665,1786116073665
1,2,R.N.,1,/ˌɑːrˈen/,/ˌɑːrˈen/,1786116073665,1786116073665
2,3,riyal,1,/riˈɑːl/,/riːˈjɑːl/,1786116073665,1786116073665
3,4,rivulet,1,/ˈrɪv.jə.lət/,/ˈrɪv.jə.lət/,1786116073665,1786116073665
4,5,riviera,1,/rɪv.iˈeə.rə/,/rɪv.iˈer.ə/,1786116073665,1786116073665

# 表导出

In [50]:
# 为单文件词典 JSONL 增加数字类型，导入端按 0-3 顺序分批写表
def with_import_type(df: pd.DataFrame, row_type: int) -> pd.DataFrame:
    typed_df = df.copy()
    typed_df.insert(loc=0, column="type", value=row_type)
    return typed_df

# 将 DataFrame 的 snake_case 列名转换为 TypeScript/Drizzle 使用的小驼峰属性名
def snake_to_camel(name: str) -> str:
    parts = name.split("_")
    return parts[0] + "".join(part[:1].upper() + part[1:] for part in parts[1:])

# 导出 JSONL 时使用小驼峰 key，避免导入端再做 key 转换
def export_jsonl(df: pd.DataFrame, path: str, mode: str = "w") -> None:
    jsonl_text = df.rename(columns=snake_to_camel).to_json(
        orient="records", lines=True, force_ascii=False
    )
    with open(path, mode, encoding="utf-8") as f:
        f.write(jsonl_text)

# 分段追加导出单文件词典 JSONL，避免不同表 concat 后产生无关 null 字段
def export_dictionary_jsonl(path: str) -> None:
    export_jsonl(with_import_type(words_tb, 0), path, mode="w")
    export_jsonl(with_import_type(word_poses_tb, 1), path, mode="a")
    export_jsonl(with_import_type(definitions_tb, 2), path, mode="a")
    export_jsonl(with_import_type(examples_tb, 3), path, mode="a")
    
export_dictionary_jsonl("./dictionary.jsonl")